inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Rails/UnknownEnv:
  Enabled: true
  Environments:
    - development
    - test
    - production

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Naming/BlockForwarding:
  EnforcedStyle: explicit

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
