default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', Rails.application.credentials.database_url) %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
